steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'start', 'vm-genai-llm', '--zone', 'us-central1-a']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'vm-genai-llm', '--zone', 'us-central1-a', '--command', 'bash /Chatbot-Codebase-Doc/script.sh']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'stop', 'vm-genai-llm', '--zone', 'us-central1-a']
